### ISSUE TITLE
CocoaPods 0.36.1beta breaks sorted search.

### ISSUE THREAD

**Issue by DenTelezhkin** [DenTelezhkin/cocoapods-sorted-search#3]
### Error

```
NoMethodError - undefined method `spec_statistics_provider' for #<Pod::Config:0x007fe0c2a98fd0>
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/sorted_search/providers/provider.rb:34:in `pod_from_spec'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/sorted_search/providers/github_provider.rb:14:in `block in fetch_data'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/sorted_search/providers/github_provider.rb:13:in `each'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/sorted_search/providers/github_provider.rb:13:in `fetch_data'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/sorted_search/providers/provider.rb:17:in `provide_sorted_specs'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-sorted-search-0.2.3/lib/pod/command/search/sorted.rb:59:in `run'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Users/Denys/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/Users/Denys/.rbenv/versions/2.1.3/bin/pod:23:in `load'
/Users/Denys/.rbenv/versions/2.1.3/bin/pod:23:in `<main>'
```

**Comment by DenHeadless** [comment]
Fixed by 0.24.0 release.
